modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="extrautilitiesrebirth"
version="1.7.3"
displayName="Extra Utilities Rebirth"
credits="Hi"
displayURL="https://www.curseforge.com/members/inzhefop/projects"
authors="inzhefop"
description='''
RELEASE [1.16.5]
'''

[[dependencies.extrautilitiesrebirth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.extrautilitiesrebirth]]
    modId="allmods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

